networks:
  default: localnet
  localnet:
    url: http://127.0.0.1:4000/api
  studio_devnet:
    url: https://studio.genlayer.com/api
  studionet:
    url: https://studio.genlayer.com/api
  testnet_asimov:
    url: https://testnet-asimov.genlayer.com/api
  testnet_bradbury:
    url: https://testnet-bradbury.genlayer.com/api
paths:
  contracts: contracts
  artifacts: test-artifacts
environment: .env
